### ISSUE TITLE
Seagrass/Macroalgae FO display

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/piney-point-analysis#3]
The FO data isn't additive (each is an independent point), could there be a series of grouped columns? Or the dotted lines like in https://shiny.tbep.org/seagrasstransect-dash/#section-summaries. Then the total (top) dotted line represents mean FO for all macro (eg a quad that has both red and cyano only gets counted 1x)?

**Comment by fawda123** [comment]
Fixed here: 996f54ca65b33becc06ac94f7da6faefb646649c

View the figure here: https://tbep-tech.github.io/piney-point-analysis/trends#seagrass
